### ISSUE TITLE
VTK version

### ISSUE THREAD

**Issue by Ryan-Zirui-Wang** [Algomorph/InfiniTAM#136]
Hi @Algomorph,

I come here from the [sobfu repo issue](https://github.com/dgrzech/sobfu/issues/2#issuecomment-475360597). I am trying to build your feature/dynamicfusion branch and got a cmake error about cannot find VTK. I installed the VTK7 with qt and python-vtk by 

```
sudo apt-get install livbvtk7-qt-dev python-vtk6
```

and the cmake can find the vtk but gave a warning:
```
-- The imported target "vtk" references the file
   "/usr/bin/vtk"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   "/usr/lib/cmake/vtk-7.1/VTKTargets.cmake"
but not all the files it references.
```

and when I build the project I got error: 
```
InfiniTAM/ITMLib/Instantiations/VoxelBlockHash/../../Utils/Visualization/ITMSceneSliceVisualizer3D.tpp: In static member function ‘static void ITMLib::ITMSceneSliceVisualizer3D<TVoxelCanonical, TVoxelLive, TIndex>::SetUpSDFColorLookupTable(vtkSmartPointer<vtkLookupTable>&, const double*, const double*, const double*, const double*, const double*, const double*)’:
InfiniTAM/ITMLib/Instantiations/VoxelBlockHash/../../Utils/Visualization/ITMSceneSliceVisualizer3D.tpp:388:81: error: no matching function for call to ‘vtkLookupTable::SetTableValue(ITMLib::VoxelColorIndex, const double*&)’
  table->SetTableValue(POSITIVE_TRUNCATED_SDF_COLOR_INDEX, positiveTruncatedColor);
```

Which version of VTK are you using? with Qt I suppose? I assume you build from the source code? how did you configure the VTK if you build from source code?

thanks a lot.

**Comment by Algomorph** [comment]
Hi, @Ryan-Zirui-Wang ,

- I was using VTK 8 with Qt, built from source. I believe I simply enabled the Qt modules in cmake-gui and did no further custom configuration.
- I don't think building with VTK should be required. The visualization components should be pruned off from this repo (perhaps to be moved into some separate repo in the future). I don't think it makes sense for you to worry about them unless you want to actually see what's going on in the SDF in detail in 3D. I recommend to simply comment out or even delete the code that uses VTK and remove it from CMakeLists.txt.

**Comment by Algomorph** [comment]
@Ryan-Zirui-Wang P.S. I've sent you an invite to collaborate directly on my fork, so you can commit directly here if you prefer and we can work together more easily.

**Comment by Ryan-Zirui-Wang** [comment]
Thanks a lot for the invitation, I'll try to remove it and see what I can contribute.

I still would give my re-implementation some time so I'll try to compare my method and yours see if anything I did is not quite right... I hope it's alright for you?

**Comment by Algomorph** [comment]
@Ryan-Zirui-Wang sure, I'm open to anything, even if you want to just grab the features from mine and simply merge them into yours that's fine. I'd be more than happy to work with you on your repository.

Please do compare both code-bases and see which course of action you find best.

A few points to keep in mind:
- There are subtle bugs I've caught in InfiniTAM, which are benign for static fusion but seemed to have an effect on level set fusion, most notably the failure to resolve hash collisions. This bug is addressed in my implementation (maybe not in the most efficient way, but still.
- As you may have noticed, I build all the specializations at once, for both CUDA and CPU, and for both PlainVoxelArray and VoxelBlockHash. Also, I have a configuration-file reading mechanism (currently based on OpenCV's data store). The goal is to eventually move away from preprocessor defines.
- One of the drawbacks of my branch is that it has, as you noticed, many dependencies, such as OpenCV, boost, and VTK. The goal was to eventually get rid of them in favor of small header-only tools or to introduce Hunter to take care of them, so they don't hinder other developers. But, for now, they are still there.

**Comment by Ryan-Zirui-Wang** [comment]
Thanks a lot for the input! It's very well written and with nice documentation. 

I have got it running after switching to Qt5 and VTK8 like you said without changing the code at all. 

The dependencies are not too bad for now, VTK and Qt are a little bit fuzzy during the cmake configuration but it's very easy to use in general.
