### ISSUE TITLE
Dockerfile

### ISSUE THREAD

**Issue by elDvd96** [Algomorph/InfiniTAM#310]
Hi, I think your code is amazing, do you perhaps have a dockerfile to share? I would really like to reproduce your results!

**Comment by Algomorph** [comment]
Unfortunately, I don't have a docker file. Luckily, the project requires very few 3rd party dependencies that can be easily built. Also, beware: I was never able to fully replicate Slavcheva's results with this code, and I've been at it for a good part of three years. The problem seems to be in the tracking algorithm itself; I think there are some subtle details missing from all the literature that are critical for the non-rigid alignment to work correctly. You may find my more recent attempts with [Neural Non-Rigid Tracking](https://github.com/Algomorph/NeuralTracking) much further along in terms of results. I don't have a docker file for that one either, but a colleague of mine that just joined in on the project was willing earlier to build one up.
